version: '3'

services:

  mongo:
    image: mongo:3
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  my-project:
    image: my-project
    ports:
      - 8085:8080
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db-prod
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo